### PR TITLE
updated for new spotify layout

### PR DESCRIPTION
**Pull request by marcosimone**
hey, I updated the extension for the new spotify layout they are rolling out.

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
Thanks Marco for this.
However I cannot see the new https://player.spotify.com as it always redirects me to the "old" https://play.spotify.com.
Any reason why you might be aware of?

**Comment by marcosimone** [comment]
I'm not sure why that happens, my roommate gets redirected to play.spotify,
but I get redirected to player. Maybe you can add code to check for either
play or player and use the correct html pattern accordingly.

**Comment by marcosimone** [comment]
Hey,
     I added support for both play and player, and in the process I
actually learned a lot about making chrome extensions (this was my first
attempt at it).  I just wanted to ask you if you're ok with me continuing
this branch and possible add more stuff to the extension and publishing my
own version of the extension with features I add.  I would mention that I
originally forked it from you're project as well.

--Marco Simone

--Marco Simone

**Comment by beaufortfrancois** [comment]
Please do so Marco!
I'm happy you've created your own version and played with Chrome Extensions.

**Comment by beaufortfrancois** [comment]
I've just pushed https://github.com/beaufortfrancois/spotify-hotkeys-chrome-extension/commit/a372fc50eb2e283c0a31d30a869feb46332a159d to support https://open.spotify.com web player. Check out new version at https://chrome.google.com/webstore/detail/spotify-web-player-hotkey/kimlaecdbfehihbiieeaeelbdkahophn and let me know if that works out for you ;)

**Pull request closed without merging**
